### ISSUE TITLE
Replace PNG illustrations with JPGs to improve performance

### ISSUE THREAD

**Issue by mikeville** [consensys-space/trusat-frontend#127]
I need to swap almost all of the PNGs for JPGs to reduce their size, but it's especially important for our website cover image, which is half a MB.

I'll make these images, but @johngribbin I'll need your help in putting these images in our AWS bucket. I hate to bother you with that, so let me know if it'd work better to show me how to do this in the future.

**Comment by johngribbin** [comment]
@mikeville Home page image now in place
