### ISSUE TITLE
JWT should not be stored in localstorage

### ISSUE THREAD

**Issue by nmclrn** [consensys-space/trusat-frontend#8]
It's insecure. See https://blog.logrocket.com/jwt-authentication-best-practices/

More generally, it's worth being acutely aware of how difficult security is in JS. Much of the following article does not apply to us, and some of it is out of date, but some of it is relevant and it's a fun read. :)
https://www.nccgroup.trust/us/about-us/newsroom-and-events/blog/2011/august/javascript-cryptography-considered-harmful/

**Comment by johngribbin** [comment]
Next step is to re-factor the code. This is a known issue 👍

**Comment by Sm00g15** [comment]
Yeah if I drop my JWT into jwt.io I can see it's data....looks like it carries my ETH address and an expiry.

**Comment by johngribbin** [comment]
will be addressed with latest release, hopefully end of this week.

**Comment by johngribbin** [comment]
https://github.com/consensys-space/trusat-frontend/pull/223
